function campoContratacao(instanceId) {
    var html = ''
    html += '<div class="row form-group" >'
    html += '    <div class="col-md-6">'
    html += '        <label class="control-label" for="nome_'+instanceId+'">Nome:</label>'
    html += '        <input class="form-control" type="text" name="nome_'+instanceId+'" id="nome_'+instanceId+'" >'
    html += '    </div>'
    html += '    <div class="col-md-3">'
    html += '        <label class="control-label" for="nivel_'+instanceId+'">Nivel de escolariedade:</label>'
    html += '        <select name="nivel_'+instanceId+'" id="nivel_'+instanceId+'" class="form-control">'
    html += '            <option value="">Selecione o nível de escolariedade</option>'
    html += '            <option value="superiorIncompleto">Superior incompleto</option>'
    html += '            <option value="SuperiorCompleto">Todos</option>'
    html += '            <option value="medioCompleto">2° Grau completo</option>'
    html += '            <option value="OutraEscolariedade">Outro</option>'
    html += '        </select>'
    html += '    </div>'
    html += '    <div class="col-md-3">'
    html += '        <label class="control-label" for="area_'+instanceId+'">Área de atuação:</label>'
    html += '        <select name="area_'+instanceId+'" id="area_'+instanceId+'" class="form-control">'
    html += '            <option value="">Todas</option>'
    html += '            <option value="Administração">Administração</option>'
    html += '            <option value="Comercial">Comercial</option>'
    html += '            <option value="Ciências Contábeis">Ciências Contábeis</option>'
    html += '            <option value="Arquitetura/Engenharia">Arquitetura/Engenharia</option>'
    html += '            <option value="Direito">Direito</option>'
    html += '            <option value="Tecnologia da Informação">Tecnologia da Informação</option>'
    html += '            <option value="OutrasAreas">Outros</option>'
    html += '        </select>'
    html += '    </div>'
    html += '</div>'
    html += '<div class="row form-group" >'
    html += '    <div class="col-md-4">'
    html += '        <label class="control-label">Aplicação</label><br>'
    html += '        <div class="custom-checkbox custom-checkbox-inline custom-checkbox-primary">'
    html += '            <input type="checkbox" id="Efetivo_'+instanceId+'" name="Efetivo_'+instanceId+'" checked> '   
    html += '            <label for="Efetivo_'+instanceId+'">Efetivo</label>'
    html += '        </div>'
    html += '        <div class="custom-checkbox custom-checkbox-inline custom-checkbox-primary">'
    html += '            <input type="checkbox" id="Estagio_'+instanceId+'" name="Estagio_'+instanceId+'" checked>'
    html += '            <label for="Estagio_'+instanceId+'">Estágio</label>  '
    html += '        </div>'
    html += '    </div>'
    html += '    <div class="col-md-4">  '
    html += '        <label class="control-label" for="dataDe_'+instanceId+'">Data de Cadastro De</label>'
    html += '        <input type="date" id="dataDe_'+instanceId+'" name="_'+instanceId+'" class="form-control form-control-sm">'
    html += '    </div>'
    html += '    <div class="col-md-4">  '
    html += '        <label class="control-label" for="dataAte_'+instanceId+'">Data de Cadastro Até</label>'
    html += '        <input type="date" id="dataAte_'+instanceId+'" name="dataAte_'+instanceId+'" class="form-control form-control-sm">'
    html += '    </div>'
    html += '</div>'
    html += '<div class="row form-group" >'
    html += '    <div class="col-md-4">'
    html += '        <label class="control-label">Status:</label><br>'
    html += '        <div class="custom-checkbox custom-checkbox-inline custom-checkbox-primary">'
    html += '            <input type="checkbox" id="Aberto_'+instanceId+'" name="Aberto_'+instanceId+'" checked>'
    html += '            <label for="Aberto_'+instanceId+'">Aberto</label>'
    html += '        </div>'
    html += '        <div class="custom-checkbox custom-checkbox-inline custom-checkbox-primary">'
    html += '            <input type="checkbox" id="Finalizado_'+instanceId+'" name="Finalizado_'+instanceId+'" checked>'
    html += '            <label for="Finalizado_'+instanceId+'">Finalizado</label>'
    html += '        </div>'
    html += '        <div class="custom-checkbox custom-checkbox-inline custom-checkbox-primary">'
    html += '            <input type="checkbox" id="Cancelado_'+instanceId+'" name="Cancelado_'+instanceId+'" checked>'
    html += '            <label for="Cancelado_'+instanceId+'">Cancelado</label>'
    html += '        </div>'
    html += '    </div>'
    html += '</div>'
    document.getElementById('camposConsulta').innerHTML += html
}
