function campoContrato(instanceId) {
    var html = ''
    html += '<div class="row form-group">'
    html += '    <div class="col-md-6">'
    html += '        <label class="control-label" for="razaoSocial_'+instanceId+'">Razão Social:</label>'
    html += '        <input type="text" id="razaoSocial_'+instanceId+'" name="razaoSocial_'+instanceId+'" class="form-control form-control-sm">'
    html += '    </div>'
    html += '    <div class="col-md-3">'
    html += '        <label class="control-label" for="CNPJ_'+instanceId+'">CNPJ:</label>'
    html += '        <input type="text" id="CNPJ_'+instanceId+'" name="CNPJ_'+instanceId+'" class="form-control form-control-sm" onkeyup="mascaraCNPJ(this)" maxlength="18">'
    html += '    </div>'
    html += '    <div class="col-md-3">'
    html += '        <label class="control-label" for="obra_'+instanceId+'">Obra:</label>'
    html += '        <input type="text" id="obra_'+instanceId+'" name="obra_'+instanceId+'" class="form-control form-control-sm">'
    html += '    </div>'
    html += '</div>'
    html += '<div class="row form-group">'
    html += '    <div class="col-md-4">'
    html += '        <label class="control-label" for="servico_'+instanceId+'">Serviço:</label>'
    html += '        <input type="text" id="servico_'+instanceId+'" name="servico_'+instanceId+'" class="form-control form-control-sm">'
    html += '    </div>'
    html += '    <div class="col-md-4">'
    html += '        <label class="control-label" for="dataDe_'+instanceId+'">Data de:</label>'
    html += '        <input type="date" id="dataDe_'+instanceId+'" name="dataDe_'+instanceId+'" class="form-control form-control-sm">'
    html += '    </div>'
    html += '    <div class="col-md-4">'
    html += '        <label class="control-label" for="dataAte_'+instanceId+'">Data ate:</label>'
    html += '        <input type="date" id="dataAte_'+instanceId+'" name="dataAte_'+instanceId+'" class="form-control form-control-sm">'
    html += '    </div>'
    html += '</div>'
    html += '<div class="row form-group">'
    html += '    <div class="col-md-4">'
    html += '        <label class="control-label">Status:</label><br>'
    html += '        <div class="custom-checkbox custom-checkbox-inline custom-checkbox-primary">'
    html += '            <input type="checkbox" id="Aberto_'+instanceId+'" name="Aberto_'+instanceId+'" checked>'
    html += '            <label for="Aberto_'+instanceId+'">Aberto</label>'
    html += '        </div>'
    html += '        <div class="custom-checkbox custom-checkbox-inline custom-checkbox-primary">'
    html += '            <input type="checkbox" id="Finalizado_'+instanceId+'" name="Finalizado_'+instanceId+'" checked>'
    html += '            <label for="Finalizado_'+instanceId+'">Finalizado</label>'
    html += '        </div>'
    html += '        <div class="custom-checkbox custom-checkbox-inline custom-checkbox-primary">'
    html += '            <input type="checkbox" id="Cancelado_'+instanceId+'" name="Cancelado_'+instanceId+'" checked>'
    html += '            <label for="Cancelado_'+instanceId+'">Cancelado</label>'
    html += '        </div>'
    html += '    </div>'
    html += '</div>'
    document.getElementById('camposConsulta').innerHTML += html
}