function campoContratoCartorio(instanceId){
    var html = ''
    html += '<div class="row form-group" >'
    html += '   <div class="col-md-2">'
    html += '       <label class="control-label" for="codde_'+instanceId+'">Codigo do cliente de:</label>'
    html += '       <input class="form-control" type="text" name="codde_'+instanceId+'" id="codde_'+instanceId+'">'
    html += '   </div>'
    html += '   <div class="col-md-2">'
    html += '       <label class="control-label" for="codate_'+instanceId+'">Codigo do cliente até:</label>'
    html += '       <input class="form-control" type="text" name="codate_'+instanceId+'" id="codate_'+instanceId+'" >'
    html += '   </div>'
    html += '   <div class="col-md-8">'
    html += '       <label class="control-label" for="nomeCliente_'+instanceId+'">Nome do cliente:</label>'
    html += '       <input class="form-control" type="text" name="nomeCliente_'+instanceId+'" id="nomeCliente_'+instanceId+'" >'
    html += '   </div>'
    html += '</div>'
    html += '<div class="row form-group" >'
    html += '   <div class="col-md-2">'
    html += '       <label class="control-label" for="codfil_'+instanceId+'">Codigo da filial:</label>'
    html += '       <input class="form-control" type="text" name="codfil_'+instanceId+'" id="codfil_'+instanceId+'">'
    html += '   </div><div class="col-md-8">'
    html += '       <label class="control-label" for="emprendimento_'+instanceId+'">Empreendimento:</label>'
    html += '       <input class="form-control" type="text" name="emprendimento_'+instanceId+'" id="emprendimento_'+instanceId+'">'
    html += '   </div>'
    html += '   <div class="col-md-1">'
    html += '       <label class="control-label" for="lote_'+instanceId+'">Lote:</label>'
    html += '       <input class="form-control" type="text" name="lote_'+instanceId+'" id="lote_'+instanceId+'" >'
    html += '   </div>'
    html += '   <div class="col-md-1">'
    html += '       <label class="control-label" for="quadra_'+instanceId+'">Quadra:</label>'
    html += '       <input class="form-control" type="text" name="quadra_'+instanceId+'" id="quadra_'+instanceId+'" >'
    html += '   </div>'
    html += ' </div>'
    html += '<div class="row form-group" >'
    html += '    <div class="col-md-4">'
    html += '        <label class="control-label" for="motivo_'+instanceId+'">Motivo:</label>'
    html += '        <select name="motivo_'+instanceId+'" id="motivo_'+instanceId+'" class="form-control" >'
    html += '            <option value="">Todos</option>'
    html += '            <option value="Inadimplência">Inadimplência</option>'
    html += '            <option value="Rescisão Não Aceita">Rescisão Não Aceita</option>'
    html += '            <option value="Risco Judicial">Risco Judicial</option>'
    html += '            <option value="Outro">Outro - Histórico</option>'
    html += '        </select>'
    html += '    </div>'
    html += '    <div class="col-md-4">'
    html += '        <label class="control-label">Status:</label><br>'
    html += '        <div class="custom-checkbox custom-checkbox-inline custom-checkbox-primary">'
    html += '            <input type="checkbox" id="Aberto_'+instanceId+'" name="Aberto_'+instanceId+'" checked>'
    html += '            <label for="Aberto_'+instanceId+'">Aberto</label>'
    html += '        </div>'
    html += '        <div class="custom-checkbox custom-checkbox-inline custom-checkbox-primary">'
    html += '            <input type="checkbox" id="Finalizado_'+instanceId+'" name="Finalizado_'+instanceId+'" checked>'
    html += '            <label for="Finalizado_'+instanceId+'">Finalizado</label>'
    html += '        </div>'
    html += '        <div class="custom-checkbox custom-checkbox-inline custom-checkbox-primary">'
    html += '            <input type="checkbox" id="Cancelado_'+instanceId+'" name="Cancelado_'+instanceId+'" checked>'
    html += '            <label for="Cancelado_'+instanceId+'">Cancelado</label>'
    html += '        </div>'
    html += '    </div>'
    html += '</div>'
    document.getElementById('camposConsulta').innerHTML += html
}